
title: Simplest Form, Coding Tutorials Weekly
email: your-email@example.com
description: The most straightforward, easy-to-understand coding tutorials on the web. New HTML, CSS, and other coding tutorials weekly.
baseurl: ""
url: "simplestform.github.io"
paginate: 5
highlighter: rouge
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
logo: /img/sf-logo-color.svg

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
